import Providers from "@/components/Providers";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Barbearia virtual",
  description: "Generated by create next app",
  icons: {
    icon: 'logo-barbearia.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
